# Generated by Django 5.0.4 on 2024-04-24 05:20

import django.core.validators
import django_extensions.db.fields
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PayrollException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("num_hours", models.PositiveIntegerField()),
                ("reason", models.TextField(validators=[django.core.validators.MinLengthValidator(50, "the field must contain at least 50 characters")])),
                ("status", models.CharField(choices=[("P", "Pending - Awaiting Supervisor Review"), ("A", "Approved - Time Amended"), ("R", "Rejected")], default="P", max_length=1)),
                ("date_submitted", django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ("last_modified", django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payroll Exception",
                "verbose_name_plural": "Payroll Exceptions",
                "db_table": "payroll_exceptions",
                "ordering": ["-date"],
            },
            bases=(models.Model, django_prometheus.models.ExportModelOperationsMixin("exceptions")),
        ),
    ]
