# Generated by Django 5.1.4 on 2025-07-03 15:39

from django.db import migrations, models

import common.upload


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="resume_cv",
            field=models.FileField(blank=True, null=True, upload_to=common.upload.UploadHandler.generate_randomized_file_name),
        ),
    ]
