# Generated by Django 5.0.4 on 2024-04-24 05:20

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("filer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliance",
            name="aps_check_verification",
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="aps_check_verification", to="filer.file"),
        ),
        migrations.AddField(
            model_name="compliance",
            name="hhs_oig_exclusionary_check_verification",
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="hhg_oig", to="filer.file"),
        ),
        migrations.AddField(
            model_name="compliance",
            name="idph_background_check_verification",
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="idph_bg_check", to="filer.file"),
        ),
        migrations.AddField(
            model_name="compliance",
            name="pre_training_verification",
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="pretraining_verification", to="filer.file"),
        ),
        migrations.AddField(
            model_name="compliance",
            name="contract_code",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="compliance.contract"),
        ),
    ]
