# Generated by Django 5.0.2 on 2024-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={
                "ordering": ["-contract_year_start"],
                "verbose_name": "State Contract",
                "verbose_name_plural": "State Contracts",
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_year_end",
            field=models.DateField(blank=True, null=True, verbose_name="End Year"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_year_start",
            field=models.DateField(blank=True, null=True, verbose_name="Start Year"),
        ),
        migrations.AddField(
            model_name="contract",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="name",
            field=models.CharField(default=" ", max_length=255),
            preserve_default=False,
        ),
    ]
