# Generated by Django 5.0 on 2024-02-13 02:41

import s3direct.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliance",
            name="aps_check_verification",
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="hhs_oig_exclusionary_check_verification",
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="idph_background_check_verification",
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="pre_training_verification",
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
