# Generated by Django 5.0.6 on 2024-07-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliance",
            name="aps_check_verification",
            field=models.FileField(blank=True, null=True, upload_to="aps_check_verification_uploads"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="hhs_oig_exclusionary_check_verification",
            field=models.FileField(blank=True, null=True, upload_to="hhs_oig_exclusionary_check_verification_uploads"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="idph_background_check_verification",
            field=models.FileField(blank=True, null=True, upload_to="idph_background_check_verification_uploads"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="pre_training_verification",
            field=models.FileField(blank=True, null=True, upload_to="pretraining_verification_uploads"),
        ),
    ]
