# Generated by Django 5.0.4 on 2024-04-16 00:07

import django.db.models.deletion
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
        ("filer", "0017_image__transparent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliance",
            name="aps_check_verification",
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="aps_check_verification", to="filer.file"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="hhs_oig_exclusionary_check_verification",
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="hhg_oig", to="filer.file"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="idph_background_check_verification",
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="idph_bg_check", to="filer.file"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="pre_training_verification",
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="pretraining_verification", to="filer.file"),
        ),
    ]
