# Generated by Django 5.0 on 2024-01-04 00:22

import django.db.models.deletion
import django_backblaze_b2.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0002_compliance_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compliance",
            name="id",
        ),
        migrations.AlterField(
            model_name="compliance",
            name="aps_check_verification",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_backblaze_b2.storage.BackblazeB2Storage,
                upload_to="nhhc-employee",
            ),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="contract_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="compliance.contract",
            ),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="compliance_profile_of",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="hhs_oig_exclusionary_check_verification",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_backblaze_b2.storage.BackblazeB2Storage,
                upload_to="nhhc-employee",
            ),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="idph_background_check_verification",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_backblaze_b2.storage.BackblazeB2Storage,
                upload_to="nhhc-employee",
            ),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="pre_training_verification",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_backblaze_b2.storage.BackblazeB2Storage,
                upload_to="nhhc-employee",
            ),
        ),
    ]
