# Generated by Django 5.0 on 2024-02-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0002_alter_compliance_aps_check_verification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliance",
            name="aps_check_verification",
            field=models.FileField(
                blank=True, null=True, upload_to="aps_check_verification"
            ),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="hhs_oig_exclusionary_check_verification",
            field=models.FileField(blank=True, null=True, upload_to="hhg-oig"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="idph_background_check_verification",
            field=models.FileField(blank=True, null=True, upload_to="idph_bg_check"),
        ),
        migrations.AlterField(
            model_name="compliance",
            name="pre_training_verification",
            field=models.FileField(
                blank=True, null=True, upload_to="pretraining_verification"
            ),
        ),
    ]
