
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: vscode
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:postgres
    command: sleep infinity
    ports:
      - 8080:8080
      - 9005:9005

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carenett_dev
    ports:
      - "5432:5432"

  dragonfly:
    image: redis
    restart: unless-stopped
    ulimits:
      memlock: -1
    volumes:
      - dragonfly-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  dragonfly-data:
