# Generated by Django 5.0.6 on 2024-06-05 04:05

import nhhc.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="cpr_verification",
            field=models.FileField(blank=True, null=True, upload_to=nhhc.utils.upload.UploadHandler("cpr_verification")),
        ),
        migrations.AlterField(
            model_name="employee",
            name="qualifications_verification",
            field=models.FileField(blank=True, null=True, upload_to=nhhc.utils.upload.UploadHandler("resume")),
        ),
    ]
