# Generated by Django 5.0 on 2024-02-08 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "get_latest_by": "-date_joined",
                "ordering": ["last_name", "first_name", "-hire_date"],
                "verbose_name": "Agency Employee",
                "verbose_name_plural": "Agency Employees",
            },
        ),
    ]
