# Generated by Django 5.0 on 2024-01-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="street_address",
            new_name="street_address1",
        ),
        migrations.AddField(
            model_name="employee",
            name="street_address2",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
