# Generated by Django 5.0.4 on 2024-04-24 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_initial"),
        ("employee", "encrypt_db"),
    ]

    operations = []
