# Generated by Django 5.0 on 2024-01-03 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_rename_street_address_employee_street_address1_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
    ]
