# Generated by Django 5.0 on 2024-02-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_alter_employee_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="termination_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
