# Generated by Django 5.0 on 2024-02-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_employee_termination_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="cpr_verification",
            field=models.FileField(
                blank=True, null=True, upload_to="verifications_cpr"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="qualifications_verification",
            field=models.FileField(
                blank=True, null=True, upload_to="verifications_resumes"
            ),
        ),
    ]
