# Generated by Django 5.0.4 on 2024-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_alter_employee_qualifications_verification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="id",
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
