# Generated by Django 5.0.4 on 2024-04-30 15:11

import datetime
import django_extensions.db.fields
import sage_encrypt.fields.asymmetric
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_merge_0002_initial_encrypt_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="sms_contact_agreement",
            field=models.BooleanField(default=True, help_text="Please Confirm that You Agree to the SMS Communication "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_first_name",
            field=sage_encrypt.fields.asymmetric.EncryptedCharField(blank=True, max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_modifed",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2024, 4, 30, 10, 11, 24, 102463)),
            preserve_default=False,
        ),
    ]
