# Generated by Django 5.0 on 2024-02-15 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0004_alter_employee_cpr_verification_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("username", "email")},
        ),
    ]
