# Generated by Django 5.0.4 on 2024-04-30 16:32

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0004_employee_sms_contact_agreement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="sms_contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name="employee",
            name="sms_contact_agreement",
            field=models.BooleanField(help_text="Please Confirm that You Agree to the SMS Communication ", null=True),
        ),
    ]
