# Generated by Django 5.0.8 on 2024-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("employee", "0004_alter_employee_cpr_verification_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["username"], name="username_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["first_name"], name="first_name_idx"),
        ),
    ]
