# Generated by Django 5.1.1 on 2024-09-15 21:17

import sage_encrypt.fields.asymmetric
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_employee_username_idx_employee_first_name_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[("NON-HISPANIC", "Non-Hispanic/Latino"), ("HISPANIC", "Hispanic/Latino"), ("UNKNOWN", "Unknown"), ("REFUSED", "Prefer Not To Disclose")],
                max_length=10485760,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENGLISH", "English"),
                    ("CHINESE", "Ethnic Chinese"),
                    ("GREEK", "Greek"),
                    ("ITALIAN", "Italian"),
                    ("LAOTIAN", "Laotian"),
                    ("ROMANIAN", "Romanian"),
                    ("TAGALOG", "Tagalog"),
                    ("YIDDISH", "Yiddish"),
                    ("ARABIC", "Arabic"),
                    ("FARSI", "Farsi"),
                    ("GUJARATI", "Gujarati"),
                    ("JAPANESE", "Japanese"),
                    ("LITHUANIAN", "Lithuanian"),
                    ("RUSSIAN", "Russian"),
                    ("UKRAINIAN", "Ukrainian"),
                    ("YUGOSLAVIAN", "Yugoslavian"),
                    ("ASSYRIAN", "Assyrian"),
                    ("FRENCH", "French"),
                    ("CREOLE", "Haitian Creole"),
                    ("MON-KHMER", "Mon-Khmer"),
                    ("MANDARIN", "Mandarin"),
                    ("SPANISH", "Spanish"),
                    ("URDU", "Urdu"),
                    ("CANTONESE", "Cantonese"),
                    ("GERMAN", "German"),
                    ("HINDI", "Hindi"),
                    ("KOREAN", "Korean"),
                    ("POLISH", "Polish"),
                    ("SWEDISH", "Swedish"),
                    ("VIETNAMESE", "Vietnamese"),
                ],
                default="ENGLISH",
                max_length=10485760,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLACK", "Black/African American"),
                    ("NATIVE", "American Indian/Alaska Native"),
                    ("ASIAN", "Asian"),
                    ("HAWAIIAN", "Native Hawaiian/Other Pacific Islander"),
                    ("WHITE", "White/Caucasian"),
                    ("OTHER", "Other Race"),
                    ("BI_RACIAL", "Two or More Races"),
                    ("UNKNOWN", "Unknown"),
                    ("REFUSED", "Prefer Not To Disclose"),
                ],
                default="UNKNOWN",
                max_length=10485760,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="social_security",
            field=sage_encrypt.fields.asymmetric.EncryptedCharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
