# Generated by Django 5.0.2 on 2024-02-17 10:47

from django.db import migrations, models

import nhhc.backends.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_alter_employee_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="cpr_verification",
            field=models.FileField(
                blank=True,
                null=True,
                storage=nhhc.backends.storage_backends.PrivateMediaStorage(),
                upload_to="verifications_cpr",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="qualifications_verification",
            field=models.FileField(
                blank=True,
                null=True,
                storage=nhhc.backends.storage_backends.PrivateMediaStorage(),
                upload_to="verifications_resumes",
            ),
        ),
    ]
