# Generated by Django 5.0.4 on 2024-05-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_employee_sms_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
