# Generated by Django 5.0.2 on 2024-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0006_alter_employee_cpr_verification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="application_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
