# Generated by Django 5.0.6 on 2024-05-14 11:04

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0006_alter_employee_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="date_joined",
        ),
        migrations.AddField(
            model_name="employee",
            name="_date_joined",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_column="date_joined", default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="application_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
