# Generated by Django 5.0.2 on 2024-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0007_employee_application_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="application_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
