# Generated by Django 5.0.2 on 2024-02-19 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0010_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
