# Generated by Django 5.0.4 on 2024-04-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcements",
            options={},
        ),
        migrations.AlterField(
            model_name="announcements",
            name="status",
            field=models.CharField(choices=[("A", "Active"), ("D", "Draft"), ("X", "Archived")], default="D", max_length=255),
        ),
        migrations.AlterModelTable(
            name="announcements",
            table=None,
        ),
    ]
