# Generated by Django 5.0.4 on 2024-05-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="status",
            field=models.CharField(choices=[("A", "Active"), ("D", "Draft"), ("X", "Archived")], db_index=True, default="D", max_length=10485760),
        ),
    ]
