# Generated by Django 5.0.2 on 2024-04-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("force_password_change", models.BooleanField(default=True)),
                ("last_password_change", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
