# Generated by Django 5.0 on 2024-01-01 09:52

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employmentapplicationmodel",
            name="home_address",
        ),
        migrations.AddField(
            model_name="clientinterestsubmissions",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientinterestsubmissions",
            name="home_address1",
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="clientinterestsubmissions",
            name="home_address2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="clientinterestsubmissions",
            name="state",
            field=localflavor.us.models.USStateField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="employmentapplicationmodel",
            name="home_address1",
            field=models.CharField(default=" ", max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employmentapplicationmodel",
            name="home_address2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="clientinterestsubmissions",
            name="zipcode",
            field=localflavor.us.models.USZipCodeField(
                blank=True, max_length=10, null=True
            ),
        ),
    ]
