# Generated by Django 5.0.2 on 2024-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentapplicationmodel",
            name="employee_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
