# Generated by Django 5.0.4 on 2024-05-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinterestsubmission",
            name="reviewed",
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="reviewed",
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
