# Generated by Django 5.0.6 on 2024-06-06 12:28

from django.db import migrations, models

import nhhc.utils.upload


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_remove_employmentapplicationmodel_cpr_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="resume_cv",
            field=models.FileField(blank=True, null=True, upload_to=nhhc.utils.upload.UploadHandler.generate_randomized_file_name),
        ),
    ]
