# Generated by Django 5.0.6 on 2024-08-02 08:26

from django.db import migrations, models

import nhhc.utils.upload


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_employmentapplicationmodel_resume_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="resume_cv",
            field=models.FileField(blank=True, null=True, upload_to=nhhc.utils.upload.UploadHandler.generate_randomized_file_name),
        ),
    ]
