# Generated by Django 5.1.1 on 2024-09-15 21:17

import nhhc.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_alter_employmentapplicationmodel_resume_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="resume_cv",
            field=models.FileField(blank=True, null=True, upload_to=nhhc.utils.upload.UploadHandler.generate_randomized_file_name),
        ),
    ]
