name: Merge Dependabot PRs

on:
  push:
  workflow_dispatch:

env:
  POETRY_VIRTUALENVS_CREATE: false
  DJANGO_CONFIGURATION: Production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Set up the correct Python version
      - name: Set Up Correct Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Fetch environment variables from Doppler
      - name: Fetch Doppler Secrets
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
          doppler-project: nhhc
          doppler-config: prod

      # Install Python dependencies using Poetry
      - name: Install Dependencies with Poetry
        uses: knowsuchagency/poetry-install@v1
        with:
          poetry-version: "latest"

      # Run tests before proceeding to merge
      - name: Run Tests
        run: |
          poetry install
          poetry check

      # Cache Python dependencies for faster builds
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Notify maintainers if the build fails
      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              body: "🚨 Build failed. Please investigate."
            })

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Automerge Dependabot PRs
      - name: Merge Dependabot PRs
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: 'main'
          merge-method: 'squash'
          commit-title: 'chore(deps): ${pullRequest.title}'
          label: 'automerge'
          merge-comment: 'Merged via auto-merge workflow 🚀'