name: Django CI – Doppler, Taskfile, Lint, Tests & Coverage

on:
  push:
    branches: [main, master, develop]
  pull_request:

permissions:
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SETTINGS_MODULE: core.settings
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb

    steps:
    - uses: actions/checkout@v4

    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v3

    - name: Load secrets from Doppler
      uses: dopplerhq/secrets-fetch-action@v1.3.0
      with:
        doppler-token: ${{ secrets.DOPPLER_TOKEN }}
        doppler-project: nhhc
        doppler-config: prod
        inject-env-vars: true

    - name: Install Taskfile CLI
      uses: arduino/setup-task@v2
      with:
        task-version: '3.44.0'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel poetry coverage pytest pytest-django pytest-cov flake8 black
        if [ -f poetry.lock ]; then
          poetry install
        elif [ -d requirements ]; then
          pip install -r requirements/base.txt
          pip install -r requirements/dev.txt
        else
          pip install -r requirements.txt
        fi
    - name: Run Black style check
      run: black --check .

    - name: Run Taskfile commands (pre-test)
      run: |
        task test -- web
